"""empty message

Revision ID: 0b763b56ff65
Revises: 
Create Date: 2023-01-24 00:23:48.807240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b763b56ff65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_shortner',
    sa.Column('short_url', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('expire_time', sa.DateTime(), nullable=True),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_shortner_short_url'), 'url_shortner', ['short_url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_shortner_short_url'), table_name='url_shortner')
    op.drop_table('url_shortner')
    # ### end Alembic commands ###
